
const CONSTANTES= {
    REGISTRO:'REGISTRO',
    LOGIN:'LOGIN',
    ESTABLECER_SESION:'ESTABLECER_SESION',
    CERRAR_SESION:'CERRAR_SESION',
    LIMPIAR_IMAGEN_SIGNUP:'LIMPIAR_IMAGEN_SIGNUP',
    CARGAR_IMAGEN_SIGNUP:'CARGAR_IMAGEN_SIGNUP',
    CLOUDINARY_NAME: 'https://api.cloudinary.com/v1_1/cloudgv/image/upload',
    CLOUDINARY_PRESET: 'akaav2pl'   ,
    CARGAR_IMAGEN_PULICACION:'CARGAR_IMAGEN_PULICACION',
    LIMPIAR_IMAGEN_PUBLICACION:'LIMPIAR_IMAGEN_PUBLICACION',
    SUBIR_PUBLICACION:'SUBIR_PUBLICACION',
    DESCARGAR_PUBLICACIONES:'DESCARGAR_PUBLICACIONES',
    AGREGAR_PUBLICACIONES_STORE:'AGREGAR_PUBLICACIONES_STORE',
    AGREGAR_AUTORES_STORE:'AGREGAR_AUTORES_STORE',
    EXITO_SUBIR_PUBLICACION:'EXITO_SUBIR_PUBLICACION',
    ERROR_SUBIR_PUBLICACION:'ERROR_SUBIR_PUBLICACION',
    LIMPIAR_SUBIR_PUBLICACION:'LIMPIAR_SUBIR_PUBLICACION',
    VERIFY_LOGIN:'VERIFY_LOGIN',
    SEND_SESSION:'SEND_SESSION',
    CLEAR_SESSION:'CLEAR_SESSION',
}

export default CONSTANTES;